name: Publish

on:
  release:
    types:
    - published

jobs:
  publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: ./.github/actions/test@main
    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        dry-run: true


