name: Publish

on:
  release:
    types:
    - published

jobs:
  publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
