name: Publish

on:
  release:
    types:
    - published

jobs:
  publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
