name: Test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@v2
    - name: Test
      uses: ./.github/actions/test@main
